export const USER_ROLES = {
  ADMIN: "ADMIN",
  USER: "USER",
};

export const FUNDRAISER_CATEGORY = {
  EDUCATION: "EDUCATION",
  MEDICAL: "MEDICAL",
  PETS: "PETS",
  BUSINESS: "BUSINESS",
  NON_PROFIT: "NON PROFIT",
  HOUSING: "HOUSING",
};

export const FUNDRAISER_STATUS = {
  DRAFT: "DRAFT",
  VERIFICATION_PENDING: "VERIFICATION_PENDING",
  VERIFIED: "VERIFIED",
  CLOSED: "CLOSED",
  REQUESTED_WITHDRAWAL: "REQUESTED_WITHDRAWAL",
  FUNDS_PROCESSED: "FUNDS_PROCESSED",
};
