const imgPath = "/images/placeholder.png";
export const fundraiserData = [
  {
    title: "Medical Treatment Fundraiser",
    description: "Helping John receive medical treatment for his illness.",
    short_description: "Urgent medical treatment needed.",
    image: imgPath,
    category: "Medical",
    target_amount: 5000,
    target_date: "2023-09-15",
    status: "Active",
    is_active: true,
    donation: 4300,
    created_by: "user_id_here",
  },
  {
    title: "Education Scholarship Fund",
    description:
      "Supporting underprivileged students with educational scholarships.",
    short_description: "Empowering young minds through education.",
    image: imgPath,
    category: "Education",
    target_amount: 10_000,
    target_date: "2023-11-30",
    status: "Active",
    is_active: true,
    donation: 5600,
    created_by: "user_id_here",
  },
  {
    title: "Animal Shelter Renovation",
    description: "Renovating the local animal shelter to provide better care.",
    short_description: "Improving conditions for shelter animals.",
    image: imgPath,
    category: "Animal Welfare",
    target_amount: 7500,
    target_date: "2023-10-20",
    status: "Active",
    is_active: true,
    donation: 5300,
    created_by: "user_id_here",
  },
  {
    title: "Environmental Cleanup Campaign",
    description:
      "Organizing a community cleanup event to protect the environment.",
    short_description:
      "Keeping our environment clean and green.Organizing a community cleanup event to protect the environment.",
    image: imgPath,
    category: "Environment",
    target_amount: 3000,
    target_date: "2023-09-30",
    status: "Active",
    is_active: true,
    donation: 1200,
    created_by: "user_id_here",
  },
  // {
  //     "title": "COVID-19 Relief Fund",
  //     "description": "Providing aid to families affected by COVID-19 pandemic.",
  //     "short_description": "Supporting those impacted by the pandemic.",
  //     "image": "/images/placeholder.png",
  //     "category": "Disaster Relief",
  //     "target_amount": 20000,
  //     "target_date": "2023-12-31",
  //     "status": "Active",
  //     "is_active": true,
  //     "donation": 18800,
  //     "created_by": "user_id_here"
  // },
  // {
  //     "title": "Arts and Culture Festival",
  //     "description": "Organizing a cultural festival to promote local artists.",
  //     "short_description": "Celebrating diversity through arts and culture.",
  //     "image": "/images/placeholder.png",
  //     "category": "Arts & Culture",
  //     "target_amount": 5000,
  //     "target_date": "2023-11-15",
  //     "status": "Active",
  //     "is_active": true,
  //     "donation": 0,
  //     "created_by": "user_id_here"
  // },
  // {
  //     "title": "Community Sports Complex",
  //     "description": "Building a sports complex for the local community.",
  //     "short_description": "Encouraging sports and fitness in the neighborhood.",
  //     "image": "image_url_here",
  //     "category": "Sports & Recreation",
  //     "target_amount": 15000,
  //     "target_date": "2024-01-31",
  //     "status": "Active",
  //     "is_active": true,
  //     "donation": 7500,
  //     "created_by": "user_id_here"
  // },
  // {
  //     "title": "Elderly Care Assistance",
  //     "description": "Providing support and care for the elderly in need.",
  //     "short_description": "Caring for our senior citizens.",
  //     "image": "/images/placeholder.png",
  //     "category": "Social Welfare",
  //     "target_amount": 8000,
  //     "target_date": "2023-10-10",
  //     "status": "Active",
  //     "is_active": true,
  //     "donation": 7200,
  //     "created_by": "user_id_here"
  // },
  // {
  //     "title": "Women's Empowerment Project",
  //     "description": "Empowering women through skill development and training.",
  //     "short_description": "Supporting women to become self-reliant.",
  //     "image": "/images/placeholder.png",
  //     "category": "Women Empowerment",
  //     "target_amount": 12000,
  //     "target_date": "2023-12-15",
  //     "status": "Active",
  //     "is_active": true,
  //     "donation": 0,
  //     "created_by": "user_id_here"
  // },
  // {
  //     "title": "Clean Water Initiative",
  //     "description": "Providing clean water access to remote communities.",
  //     "short_description": "Ensuring access to safe drinking water.",
  //     "image": "/images/placeholder.png",
  //     "category": "Public Health",
  //     "target_amount": 6000,
  //     "target_date": "2023-09-30",
  //     "status": "Active",
  //     "is_active": true,
  //     "donation": 5500,
  //     "created_by": "user_id_here"
  // }
];

export const statsItems = [
  {
    category: "Our Professional Teams",
    value: "100+",
  },
  {
    category: "Years of Experience",
    value: "10+",
  },
  {
    category: "Fastest Growing Agency",
    value: "90%",
  },
  {
    category: "Happy Customers",
    value: "300+",
  },
];
