export const USER_ROLES = {
  ADMIN: "ADMIN",
  USER: "USER",
};

export const FUNDRAISER_CATEGORY = {
  EDUCATION: "EDUCATION",
  MEDICAL: "MEDICAL",
  PETS: "PETS",
  BUSINESS: "BUSINESS",
  NON_PROFIT: "NON PROFIT",
  HOUSING: "HOUSING",
};

export const FUNDRAISER_STATUS = {
  CREATED: "CREATED",
  VERIFIED: "VERIFIED",
  CLOSED: "CLOSED",
  REQUEST_WITHDRAWALS: "REQUEST_WITHDRAWALS",
  FUNDS_PROCESSED: "FUNDS_PROCESSED",
};
